name: DuckDB Node Client API
on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: false

jobs:

  linux-nodejs:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - name: Bindings - Install, Configure, and Build
        working-directory: alt/bindings
        run: npm i
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: npm test

  osx-nodejs:
    name: Mac OS X
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt

      - name: Bindings - Install, Configure, and Build
        working-directory: alt/bindings
        run: npm i
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: npm test

  win-nodejs:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - name: Bindings - Install, Configure, and Build
        working-directory: alt/bindings
        run: npm i
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: npm test
