name: DuckDB Node Client API
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      linux:
        description: 'Linux'
        type: boolean
        required: true
        default: false
      macos:
        description: 'Mac OS'
        type: boolean
        required: true
        default: false
      windows:
        description: 'Windows'
        type: boolean
        required: true
        default: false
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: false

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.linux }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test

  macos:
    name: Mac OS X
    runs-on: macos-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.macos }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test

  windows:
    name: Windows
    runs-on: windows-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.window }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test
