name: DuckDB Node Client API
on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: false

jobs:

  linux-nodejs:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test

  osx-nodejs:
    name: Mac OS X
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test

  win-nodejs:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test
