name: DuckDB Node Client API
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      publish_dry_run:
        description: 'Publish Dry Run'
        type: boolean
        required: true
        default: true
      linux:
        description: 'Run on Linux'
        type: boolean
        required: true
        default: false
      publish_linux_x64:
        description: 'Publish Bindings for Linux x64'
        type: boolean
        required: true
        default: false
      publish_bindings:
        description: 'Publish Bindings (from Linux)'
        type: boolean
        required: true
        default: false
      publish_api:
        description: 'Publish API (from Linux)'
        type: boolean
        required: true
        default: false
      macos:
        description: 'Run on Mac OS'
        type: boolean
        required: true
        default: false
      publish_darwin_arm64:
        description: 'Publish Bindings for Darwin ARM64'
        type: boolean
        required: true
        default: false
      windows:
        description: 'Run on Windows'
        type: boolean
        required: true
        default: false
      publish_win32_x64:
        description: 'Publish Bindings for Win32 x64'
        type: boolean
        required: true
        default: false
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: false

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.linux }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test
      
      - name: Publish - Config Auth Token
        if: ${{ inputs.publish_linux_x64 || inputs.publish_bindings || inputs.publish_api }}
        run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish - Bindings - Linux x64
        if: ${{ inputs.publish_linux_x64 }}
        working-directory: alt/bindings/pkgs/@duckdb/node-bindings-linux-x64
        run: pnpm publish ${{ inputs.publish_dry_run && '--dry-run' || '' }} --publish-branch ${{ github.ref_name }}
      
      - name: Publish - Bindings
        if: ${{ inputs.publish_bindings }}
        working-directory: alt/bindings/pkgs/@duckdb/node-bindings
        run: pnpm publish ${{ inputs.publish_dry_run && '--dry-run' || '' }} --publish-branch ${{ github.ref_name }}

      - name: Publish - API
        if: ${{ inputs.publish_api }}
        working-directory: alt/bindings/pkgs/@duckdb/node-api
        run: pnpm publish ${{ inputs.publish_dry_run && '--dry-run' || '' }} --publish-branch ${{ github.ref_name }}

  macos:
    name: Mac OS X
    runs-on: macos-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.macos }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test
      
      - name: Publish - Config Auth Token
        if: ${{ inputs.publish_darwin_arm64 }}
        run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish - Bindings - Darwin ARM64
        if: ${{ inputs.publish_darwin_arm64 }}
        working-directory: alt/bindings/pkgs/@duckdb/node-bindings-darwin-arm64
        run: pnpm publish ${{ inputs.publish_dry_run && '--dry-run' || '' }} --publish-branch ${{ github.ref_name }}

  windows:
    name: Windows
    runs-on: windows-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.window }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: alt
      
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Workspace - Install
        working-directory: alt
        run: pnpm install

      - name: Bindings - Build
        working-directory: alt/bindings
        run: pnpm run build
      
      - name: Bindings - Test
        working-directory: alt/bindings
        run: pnpm test
      
      - name: API - Build
        working-directory: alt/api
        run: pnpm run build
      
      - name: API - Test
        working-directory: alt/api
        run: pnpm test
      
      - name: Publish - Config Auth Token
        if: ${{ inputs.publish_win32_x64 }}
        run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish - Bindings - Win32 x64
        if: ${{ inputs.publish_win32_x64 }}
        working-directory: alt/bindings/pkgs/@duckdb/node-bindings-win32-x64
        run: pnpm publish ${{ inputs.publish_dry_run && '--dry-run' || '' }} --publish-branch ${{ github.ref_name }}
